"use strict";
(() => {
    let avenger = 123;
    let exist;
    let power;
    let avengerr = 123;
    let existt;
    let powerr;
    avengerr = 'dr stone';
    console.log(avengerr.charAt(0));
    avengerr = 125.255635;
    console.log(avengerr.toFixed(2));
    console.log(existt);
    console.log(power);
    let avengerrr;
    let existtt;
    let powerrr;
    avengerrr = 'dr stone';
    console.log(avengerrr.charAt(0));
    avengerrr = 125.255635;
    console.log(avengerrr.toFixed(2));
    console.log(existtt);
    console.log(powerrr);
    let avengerrrr;
    let existttt;
    let powerrrr;
    avengerrrr = 'dr stone';
    console.log(avengerrrr.charAt(0));
    avengerrrr = 125.255635;
    console.log(avengerrrr.toFixed(2));
    console.log(existttt);
    console.log(powerrrr);
})();
//# sourceMappingURL=any.js.map